name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "0 */10 * * *"  # Every 10 hours
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create empty commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit --allow-empty -m "keepalive: prevent Streamlit sleep [skip ci]" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin HEAD:main
