name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "0 */10 * * *"  # Every 10 hours
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "keepalive-bot"
          git config user.email "keepalive@example.com"

      - name: Make empty commit
        run: |
          git commit --allow-empty -m "keepalive: prevent Streamlit sleep [skip ci]" || echo "No changes to commit"

      - name: Push to GitHub
        run: |
          git push
